### ISSUE TITLE
Adjusting threshold before changing initial frame results in error

### ISSUE THREAD

**Issue by jrembold** [jrembold/AllSky#5]
Upon loading a new video, if the threshold slider is moved before the initial frame is moved, a non-fatal error occurs.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "PhotometryGUI.py", line 190, in Threshold
    ThresholdView = Photometry.Threshold(self.ImageStack[:,:,self.FrameNo],
AttributeError: 'GUI' object has no attribute 'FrameNo'
```

**Comment by lukegalbraithrussell** [comment]
Fixed! FrameNo is now initially set to the first frame, instead of not being called until frame slider is used.
